using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdvanceMyProgrammingSkills
{
	class Problem2
	{
		// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with
		// 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in 
		// the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

		public static void Fibonacci()
		{
			int[] f = new int[100];
			f[0] = 1;
			f[1] = 2;

			int sum = 0;
			int i = 0;
			while (f[i]<4000000)
			{				
				f[i + 2] = f[i] + f[i + 1];

				if (f[i] % 2 == 0)
				{
					sum = sum + f[i];
				}
				i++;
			}			

			Console.WriteLine(sum);
			
		}
	}
}
